package com.huixw.web.entity;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Tue Nov 10 19:29:35 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbggenerated  Tue Nov 10 19:29:35 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.age
	 * @mbggenerated  Tue Nov 10 19:29:35 CST 2015
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.remark
	 * @mbggenerated  Tue Nov 10 19:29:35 CST 2015
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Tue Nov 10 19:29:35 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Tue Nov 10 19:29:35 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbggenerated  Tue Nov 10 19:29:35 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbggenerated  Tue Nov 10 19:29:35 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.age
	 * @return  the value of user.age
	 * @mbggenerated  Tue Nov 10 19:29:35 CST 2015
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.age
	 * @param age  the value for user.age
	 * @mbggenerated  Tue Nov 10 19:29:35 CST 2015
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.remark
	 * @return  the value of user.remark
	 * @mbggenerated  Tue Nov 10 19:29:35 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.remark
	 * @param remark  the value for user.remark
	 * @mbggenerated  Tue Nov 10 19:29:35 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}